
services:
  database:
    image: postgres:17.9-trixie
    container_name: bafrapy-postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - bafrapy-postgresql-data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d:ro
    networks:
      - bafrapy-network
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      start_period: 5s

  directus:
    build:
      context: ./directus
      dockerfile: Dockerfile
    container_name: bafrapy-directus
    networks:
      - bafrapy-network
    ports:
      - ${DIRECTUS_EXTERNAL_PORT}:${DIRECTUS_PORT}
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${DIRECTUS_ADMIN_TOKEN}
      EXTENSIONS_AUTO_RELOAD: 'true'
    volumes:
      - bafrapy-directus-data:/directus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8055/health || exit 1"]
      start_period: 5s

  gizmosql:
    build:
      context: ./gizmosql
      dockerfile: Dockerfile
    container_name: bafrapy-ducklake
    ports:
      - "${GIZMOSQL_EXTERNAL_PORT}:${GIZMOSQL_PORT}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      TLS_ENABLED: "0"
      GIZMOSQL_USERNAME: ${GIZMOSQL_USERNAME}
      GIZMOSQL_PASSWORD: ${GIZMOSQL_PASSWORD}
      

      DATABASE_FILENAME: "/opt/gizmosql/data/${GIZMOSQL_DATABASE}.duckdb"
      INIT_SQL_COMMANDS_FILE: "/opt/gizmosql/init/init_ducklake.sql"

      PGHOST: database
      PGPORT: ${DB_PORT}
      PGDATABASE: ducklake
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}

    volumes:
      - bafrapy-ducklake-data:/opt/gizmosql/data
      - ./gizmosql/init:/opt/gizmosql/init:ro
    networks:
      - bafrapy-network

networks:
  bafrapy-network:
    name: bafrapy-network
    driver: bridge

volumes:
  bafrapy-postgresql-data:
    name: bafrapy-postgresql-data
    external: true

  bafrapy-directus-data:
    name: bafrapy-directus-data
    external: true

  bafrapy-ducklake-data:
    name: bafrapy-ducklake-data
    external: true