services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    ports:
      - '8080:80'
    environment:
      PMA_HOST: bafrapy-mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 750M 
    networks:
      - bafrapy-network

networks:
  bafrapy-network:
    external: true

