
services:
  clickhouse:
    container_name: bafrapy_clickhouse
    image: clickhouse/clickhouse-server:23.9.5-alpine
    environment:
      - CLICKHOUSE_USER=${CH_USER}
      - CLICKHOUSE_PASSWORD=${CH_PASSWORD}
      - CLICKHOUSE_DB=${CH_DATABASE}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-log:/var/log/clickhouse-server
      - clickhouse-config:/etc/clickhouse-server
      - ./clickhouse-settings/custom-config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      - ./clickhouse-settings/custom-user.xml:/etc/clickhouse-server/users.d/custom-user.xml
    ports:
      - ${CH_HTTP_EXTERNAL_PORT}:${CH_HTTP_PORT}
      - ${CH_NATIVE_EXTERNAL_PORT}:${CH_NATIVE_PORT}
    networks:
      - bafrapy-network

  database:
    image: postgres:17.9-trixie
    container_name: bafrapy-postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - bafrapy-postgresql-data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d:ro
    networks:
      - bafrapy-network
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      start_period: 5s

  directus:
    build:
      context: ./directus
      dockerfile: Dockerfile
    container_name: bafrapy-directus
    networks:
      - bafrapy-network
    ports:
      - ${DIRECTUS_EXTERNAL_PORT}:${DIRECTUS_PORT}
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      EXTENSIONS_AUTO_RELOAD: 'true'
    volumes:
      - bafrapy-directus-data:/directus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8055/health || exit 1"]
      start_period: 5s

networks:
  bafrapy-network:
    name: bafrapy-network
    driver: bridge

volumes:
  bafrapy-postgresql-data:
    name: bafrapy-postgresql-data
    external: true

  bafrapy-directus-data:
    name: bafrapy-directus-data
    external: true

  clickhouse-data:
    name: clickhouse-data
  clickhouse-config:
    name: clickhouse-config
  clickhouse-log:
    name: clickhouse-log